---

- name: Get variables based on OS type
  ansible.builtin.include_tasks:
    file: vars.yml

- name: Install LSB packages
  ansible.builtin.package:
    name: "{{ lsb_packages }}"
    state: present
